language: node_js
node_js:
 - '0.10'
notifications:
  slack:
    secure: N3sET5rk3iqlkrweGZKDlKDJzfNFE4fVF8X14KHu/eMbe6r65zzPhaAtl94W7XDt5dO5Pb1jILN1wg0ma52/SfsSnklYFZ75+Lbmmi39KQLIqJJopY6jgX55mvxvTRm0gOh5WYfotbCW0ywHOR5TMzveZV4eumPwM0dIKlZ2vLPov98uRpyHBDLT1k/itwTimX9NLwaw/FsYDRmw3/IfF4HnIe/8crh1QAesuzwpA/uQErvYlDJVbagdjgO2huTXmt430jVt86OsgMKNshCVGeuzLU+BINIOXpU56YW9UerFNWp6bwxuvNpDnMZh9qFHtpwJeyJR1rfm5lk/0XCTzORNxk44A9sR92XX6UeW5PuHY6VC1XcerlUGZujUKxoBgAx/zExTU+XlnELyIzxisXilRr13MoK5hr+ExU+a1Qc0hxTj76hj33RxrJV7CDUFdasTgrEHwNrwCz7X+/jrPYfx58SkT62s4hD7Ff08mARUxZ+LPJwL7JE82leFsADRL4vMAqo/nwWcTfZ73S6GBMvCdYjqcXHitki+u4pJtvWSu0UOm5ZKQK7CUVbM+3XAt9RpkpMeJwvFEevLGjfEHyVZZLLPUB28xs0E7afNq6mRV1C7/Izt0kS0Jp6mBXC9rexjkLhMC4zqYargzCBlhecoFo4L1w2J3Tjj37mYZ74=
